# ---
- hosts: ops
  gather_facts: False
  pre_tasks:
  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    register: output
    changed_when: output.stdout != ""
    become: true
    ignore_errors: true
    tags: always
  - name: Gather Facts after inital Setup
    setup:
    tags: always

  roles:
  - role: gve.up2date
    become: true
  - role: gve.scicd
    become: true
  - role: gve.sshd
    become: true
  - role: gve.hardened
    become: true
  - role: gve.sysctl
    become: true
  - role: gve.honeypot
    become: true
  - role: gve.ufw
    become: true
  - role: gve.fail2ban
    become: true

- hosts: threeyd
  roles:
  - role: gve.health
    become: true

- hosts: immigrants
  roles:

- hosts: local
  roles:
